docs: drink
r0gue-io/pop-drink pull request #22
Opened 2024-10-16 21:27 UTC by Daanvdplas

I would suggest to read the docs by getting it locally and see how it reads and if everything is clear. I changed the naming back to `ApiError` as I think it was the correct name. It refers to the error type in the api. My apologies for that...

I removed many of the readme docs as many was already covered somewhere else. Not repeating ourselves minimises the amount of code to maintain and chances for small mistakes.

Please read the code examples provided carefully as I found mistakes in your PR. Imagine you looking into a new library and you find out there are mistakes in the example docs? To me this wouldn't be a good sign. Therefore another reason to keep things simple and short (often also a sign the code is well understood :) ).

Please make final changes in a single commit (so I can check) and merge into your PR. Then, `feat-runtime_error` can be merged too. Your readme PR won't be necessary if you agree with these changes.

2024-10-17 08:09 UTC, chungquantin requested changes
There are a few nitpicks that need to tackle. Aside from that, I like your doc. It is clean to me. Thanks for making these changes .

2024-10-17 08:09 UTC, chungquantin commented on crates/pop-drink/src/lib.rs
> +	pub use pop_runtime_devnet::{RuntimeError::*, Runtime};
Conflict exports. `Session` is exported here, while the `Session` type for testing is exported in the next line.

2024-10-17 08:09 UTC, chungquantin commented on crates/pop-drink/src/error.rs
>  #[track_caller]
```suggestion
#[track_caller]
#[allow(unused)]
```

2024-10-17 08:09 UTC, chungquantin commented on crates/pop-drink/src/error.rs
> +/// fn test_custom_error(mut session: Session) {
Thanks for this example code, looks better.

2024-10-17 08:09 UTC, chungquantin commented on crates/pop-drink/src/error.rs
> +///		let result = call::<Pop, (), CustomError>(session, "hello_world", vec![], None);
Need to reformat. Wrong indentation.

2024-10-17 08:09 UTC, chungquantin commented on crates/pop-drink/src/error.rs
> +///		...,
Wrong indentation.

2024-10-18 08:20 UTC, Daanvdplas commented
Thank you, resolved all your comments!

2024-10-18 08:20 UTC, merged